config/routes.rb
Rails.application.routes.draw do

  devise_for :users
   root 'welcome#index'
   
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
   # :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :confirmable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hillsboard</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>

    <% if alert %>
    <p class="alert">
      <%= alert %>
    </p>
<% elsif notice %>
    <p class="notice">
      <%= notice %>
    </p>
<% end %>

    <%= yield %>

  </body>
</html>

app/views/welcome/index.html.erb
<div id="background">
  	<header class="cf">
  	    <div class="wrapper_wide">
  	    	<a href="#" id="logo">Hillsboard</a>
  		    <nav>
  		      <ul>
  		   	   <% unless user_signed_in? %>
					<li><%= link_to "Explore", users_path %></li>
					<li><%= link_to "Sign In", new_user_session_path %></li>
					<li><%= link_to "Create Account", new_user_registration_path %></li>
				<% else %>
					
					<li><a href="#">Dashboard</a></li>
					<li><a href="#">Explore</a></li>
					
					<li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
				<% end %>
  		      </ul>
  		    </nav>
  		 </div>	
  	</header>
  	<div class="wrapper_skinny">
  	    <h1>Discover your new favorite<br> songs, or create your own.</h1>
  	    <%= link_to "Create Account", new_user_registration_path, class: "button button_highlight" %>
         <a href="#" class="button button_white">Explore</a>
  	</div>
</div>